### ISSUE TITLE
DLL not found?

### ISSUE THREAD

**Issue by UwQ-Official** [YuLun-bili/Teardown-Translation-Converter#1]
![image](https://github.com/YuLun-bili/Teardown-Translation-Converter/assets/136825306/8baaf341-f8ae-4ae7-9438-a81dda02c4b6)

Pretty self-explanatory :/

**Comment by YuLun-bili** [comment]
uhhh I'm not sure about this one honestly. I don't have such .dll on my device and it runs normally

**Comment by YuLun-bili** [comment]
get it from [rtc](https://github.com/samyeyo/rtc)

**Comment by YuLun-bili** [comment]
Would update it later so that it won't require the dependency
